task: 'zju_mocap'
subject: 'p394'
experiment: 'suject_394'

ddp: False

trainer_module: 'core.train.trainers.monohuman.trainer'
network_module: 'core.nets.monohuman.network'

index_a: 196
index_b: 246

debug: False
##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.monohuman.monodata'
  dataset: 'zju_394_train'
  perturb: 1.        # only for training, set to 0. for no jitter, 1. for jitter
  batch_size: 1
  shuffle: True
  drop_last: False
  maxiter: 400000
  lr: 0.0005  # 5e-4
  lr_mweight_vol_decoder: 0.000005 # 5e-5
  lr_pose_decoder: 0.00005        # 5e-5
  lr_non_rigid_mlp: 0.00005       # 5e-5
  lr_compress_fc: 0.0005
  lr_forward_mlp: 0.00005 
  lr_backward_mlp: 0.00005 
  lrate_decay: 500
  optimizer: 'adam'
  log_interval: 20
  save_checkpt_interval: 2000
  save_model_interval: 50000
  ray_shoot_mode: 'patch'
  lossweights:
    lpips: 1.0
    mse: 0.2

blend_net:
  module: 'core.nets.monohuman.blend.mlp_network'

feature_extractor:
  module: 'core.nets.monohuman.feature_extract.feature_extractor'

projector:
  module: 'core.nets.monohuman.projector.projector'

progress:
  dataset_module: 'core.data.monohuman.monodata'
  dataset: 'zju_394_test'

movement:
  dataset_module: 'core.data.monohuman.monodata'
  dataset: 'zju_394_test'

freeview:
  dataset_module: 'core.data.monohuman.freeview'
  dataset: 'zju_394_test'

tpose:
  dataset_module: 'core.data.monohuman.tpose'
  dataset: 'zju_394_test'

text:
  dataset_module: 'core.data.monohuman.text'
  dataset: 'zju_394_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5

# # reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  sample_subject_ratio: 0.8
  N_patches: 3
  size: 32      # [Patch] size of patch
fg_thread: 0.3
netchunk_per_gpu: 50000 # number of pts sent through network in parallel, decrease if running out of memory
chunk: 1024   # 32768=1024*32, number of rays processed in parallel, decrease if running out of memory
n_gpus: 1